build:
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker login -u gbraad -p $DOCKER_PASSWORD
  script:
    - docker build -t registry.gitlab.com/gbraad/zerotier:latest . 
    - docker push registry.gitlab.com/gbraad/zerotier:latest
    - docker tag registry.gitlab.com/gbraad/zerotier gbraad/zerotier:latest
    - docker push gbraad/zerotier:latest
  only:
    - master
  when: manual
